name = "wizard-online"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [{name = "GAME", class_name = "GameManager"}]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_classes = ["GameManager"]
deleted_classes = ["GameRoom"]

[limits]
cpu_ms = 100