name = "wizard-online"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [{name = "GAME", class_name = "GameRoom"}]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]
